### ISSUE TITLE
Interval set to 0 in query packs

### ISSUE THREAD

**Issue by benbasscom** [palantir/osquery-configuration#10]
Hi there.

It looks like the yaml files got hit with the fleetctl conversion bug where the interval get set to 0 when converting.  Can you update the packs with the correct intervals?

Thank you!

For example; 

  - description: Track the percentage of total CPU time utilized by $endpoint_security_tool
    interval: 0
    name: endpoint_security_tool_perf
    query: endpoint_security_tool_perf
    snapshot: true

**Comment by clong** [comment]
Ah! I just came across this as well today. Will get this fixed ASAP.

**Comment by clong** [comment]
This should be fixed now. Sorry about that and thanks for the report!
