### ISSUE TITLE
errors for osquery config

### ISSUE THREAD

**Issue by rnolette** [palantir/osquery-configuration#6]
Hello,
I attempted to run the osquery config verbatim from this repo and received the error 

> E0424 14:24:07.104848  5115 init.cpp:579] [Ref #1629] osqueryd initialize failed: Could not initialize database

What version of osquery did you develop your config for?

**Comment by clong** [comment]
Hi @rnolette - this indicates a problem with the osquery database and is likely not an issue with the config itself.
