### ISSUE TITLE
Question about how to interpret results

### ISSUE THREAD

**Issue by massimonewsuk** [palantir/osquery-configuration#8]
So we've installed this on one of our endpoints as per the quickstart instructions in order to trial it. We're seeing the following files generated after almost 24 hours of use:
![image](https://user-images.githubusercontent.com/35228622/47484108-d3500000-d832-11e8-84d5-b077aa276994.png)

How are we supposed to interpret these results? What sort of things are we supposed to look out for? Does osquery alert us or do we need to manually review these files periodically etc? Are there any blog posts or tutorials that can give us more info about how to review these files?

Also note that the directory on windows ends in `/log` not `/logs` as the quickstart says.

**Comment by clong** [comment]
Hi @massimonewsuk,

> How are we supposed to interpret these results? What sort of things are we supposed to look out for? 

That's really up to you - osquery doesn't really come with a "standard" configuration and different teams use it for a variety of things.

> Does osquery alert us or do we need to manually review these files periodically etc? 

I think most orgs ingest these logs into a centralized logging platform (e.g. ELK, Splunk, Graylog) and review them through those tools. 

> Are there any blog posts or tutorials that can give us more info about how to review these files?

Here's a few: 

* https://hackernoon.com/malware-analysis-using-osquery-part-1-78f5f617cc19
* https://medium.com/@clong/osquery-for-security-b66fffdf2daf
* https://www.digitalocean.com/community/tutorials/how-to-monitor-your-system-security-with-osquery-on-ubuntu-16-04
* https://blog.rapid7.com/2016/05/09/introduction-to-osquery-for-threat-detection-dfir/

Good luck and happy hunting!
